/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminApp: typeof import('./src/components/admin/AdminApp.vue')['default']
    AdminNavBar: typeof import('./src/components/admin/layouts/AdminNavBar.vue')['default']
    AdminTest: typeof import('./src/components/admin/AdminTest.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    ContentPage: typeof import('./src/components/paper/ContentPage.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FeedBackPage: typeof import('./src/components/feedback/FeedBackPage.vue')['default']
    FooterBar: typeof import('./src/components/layouts/FooterBar.vue')['default']
    GroupPage: typeof import('./src/components/group/GroupPage.vue')['default']
    ListPage: typeof import('./src/components/paper/ListPage.vue')['default']
    LoginPage: typeof import('./src/components/account/LoginPage.vue')['default']
    NavBar: typeof import('./src/components/layouts/NavBar.vue')['default']
    NotFoundPage: typeof import('./src/components/NotFoundPage.vue')['default']
    ProfilePage: typeof import('./src/components/account/ProfilePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartScreen: typeof import('./src/components/home/StartScreen.vue')['default']
    TestPage: typeof import('./src/components/test/TestPage.vue')['default']
    WordView: typeof import('./src/components/app/WordView.vue')['default']
  }
}
